### ISSUE TITLE
Multi-Tautulli Not Functioning

### ISSUE THREAD

**Issue by justinglock40** [PTS-Team/Apps-Core#7]
`
Traceback (most recent call last):

  File "/app/tautulli/PlexPy.py", line 24, in <module>

    from Tautulli import main

  File "/app/tautulli/Tautulli.py", line 38, in <module>

    import plexpy

  File "/app/tautulli/plexpy/__init__.py", line 38, in <module>

    import activity_handler

  File "/app/tautulli/plexpy/activity_handler.py", line 24, in <module>

    import activity_processor

  File "/app/tautulli/plexpy/activity_processor.py", line 21, in <module>

    import database

  File "/app/tautulli/plexpy/database.py", line 25, in <module>

    import logger

  File "/app/tautulli/plexpy/logger.py", line 30, in <module>

    import helpers

  File "/app/tautulli/plexpy/helpers.py", line 48, in <module>

    from plexpy.api2 import API2

  File "/app/tautulli/plexpy/api2.py", line 39, in <module>

    import notification_handler

  File "/app/tautulli/plexpy/notification_handler.py", line 43, in <module>

    from newsletter_handler import notify as notify_newsletter

  File "/app/tautulli/plexpy/newsletter_handler.py", line 29, in <module>

    NEWSLETTER_SCHED = BackgroundScheduler()

  File "/app/tautulli/lib/apscheduler/schedulers/base.py", line 82, in __init__

    self.configure(gconfig, **options)

  File "/app/tautulli/lib/apscheduler/schedulers/base.py", line 121, in configure

    self._configure(config)

  File "/app/tautulli/lib/apscheduler/schedulers/background.py", line 29, in _configure

    super(BackgroundScheduler, self)._configure(config)

  File "/app/tautulli/lib/apscheduler/schedulers/base.py", line 689, in _configure

    self.timezone = astimezone(config.pop('timezone', None)) or get_localzone()

  File "/app/tautulli/lib/tzlocal/unix.py", line 131, in get_localzone

    _cache_tz = _get_localzone()

  File "/app/tautulli/lib/tzlocal/unix.py", line 125, in _get_localzone

    raise pytz.UnknownTimeZoneError('Can not find any timezone configuration')

pytz.exceptions.UnknownTimeZoneError: 'Can not find any timezone configuration'`

**Comment by MrDoobPG** [comment]
multi removed
